---
- name: List available PowerVC Images
  hosts: localhost
  tasks:
    - name: Retrieve list of all AIX images
      os_image_info:
      register: result

    - name: Print image list
      debug:
        msg: "{{ result }}"
